

# This file was *autogenerated* from the file /Users/seanross/kingdom_of_god/home-base/current_hunts/big-thinkers/research-systems/bsd-conjecture/u-equals-1-clean/final_lp_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_25 = Integer(25); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_100 = Integer(100)# Final check: does Sage's Lp(E,0) agree with interpolation (1-1/alpha)^2 * L(E,1)/Omega?
E = EllipticCurve('11a1')
p = _sage_const_7 
Lp = E.padic_lseries(p)

# Get the constant term of the series in a robust way
series = Lp.series(prec=_sage_const_8 , n=_sage_const_5 )
print(f"Lp series: {series}")

# Parse out the constant term T^0 coefficient
# The coefficient is itself a p-adic number
zero_coeff = series[_sage_const_0 ]
print(f"Lp(E, T=0) (constant coefficient of series) = {zero_coeff}")
print(f"  valuation = {zero_coeff.valuation()}")

# Compute the interpolation value in Q_p
Zp_7 = Zp(_sage_const_7 , prec=_sage_const_25 )
R = PolynomialRing(Zp_7, 'x')
f = R.gen()**_sage_const_2  + _sage_const_2 *R.gen() + _sage_const_7 
roots = f.roots()
alpha = None
for r, _ in roots:
    if r.valuation() == _sage_const_0 :
        alpha = r
        break

euler = (_sage_const_1  - _sage_const_1 /alpha)**_sage_const_2 
L_ov_Om = Zp_7(_sage_const_1 ) / Zp_7(_sage_const_5 )
interp = euler * L_ov_Om
print(f"\nInterpolation formula (1-1/alpha_7)^2 * (1/5) = {interp}")
print(f"  valuation = {interp.valuation()}")

# Are they equal?
print(f"\nFirst 8 digits of series constant: {str(zero_coeff)[:_sage_const_100 ]}")
print(f"First 8 digits of interp value:    {str(interp)[:_sage_const_100 ]}")

# Compare digit by digit
diff = zero_coeff - interp
print(f"\nDifference (series - interp): {diff}")
print(f"Valuation of difference: {diff.valuation()}")

