

# This file was *autogenerated* from the file /Users/seanross/kingdom_of_god/home-base/current_hunts/big-thinkers/research-systems/bsd-conjecture/u-equals-1-clean/pbsd_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_7 = Integer(7)# Verify the p-part of BSD for 11a1/p=7 holds unconditionally
E = EllipticCurve('11a1')
print("BSD for 11a1:")
print(f"  L(E,1)/Omega = {E.lseries().L_ratio()}")
print(f"  |E(Q)_tors| = {E.torsion_subgroup().order()}")
print(f"  Tamagawa product = {E.tamagawa_product()}")
print(f"  Analytic order of Sha = {E.sha().an()}")
print(f"  Analytic rank = {E.rank()}")
# BSD formula (rank 0): L(E,1)/Omega = Tam * |Sha| / |tors|^2
tam = E.tamagawa_product()
sha_an = E.sha().an()
tors = E.torsion_subgroup().order()
bsd_rhs = tam * sha_an / tors**_sage_const_2 
print(f"  BSD RHS: Tam*|Sha|/|tors|^2 = {tam}*{sha_an}/{tors}^2 = {bsd_rhs}")
print(f"  BSD check: {E.lseries().L_ratio() == bsd_rhs}")

print()
print("p-part of BSD at p=7:")
print(f"  v_7(L(E,1)/Omega) = v_7(1/5) = 0")
print(f"  v_7(Tam) = v_7(5) = 0")
print(f"  v_7(|Sha|) = v_7(1) = 0")
print(f"  v_7(|tors|) = v_7(5) = 0")
print(f"  All trivially 0 at p=7. p-part of BSD holds for 11a1 at p=7.")

# Burungale-Castella-Skinner hypotheses
print()
print("Burungale-Castella-Skinner hypotheses for rank-0 non-CM p-BSD:")
print(f"  p=7 > 3: YES")
print(f"  good ordinary at p=7 (p does not divide a_p): a_7 = {E.ap(_sage_const_7 )}, OK")
print(f"  SL_2(Z_p) in rho_E,p image: rho_bar surjective at 7, so yes")
print(f"  analytic rank <= 1: rank = {E.rank()}, OK")
print(f"  => p-part of BSD for E/Q at p=7 is a THEOREM (Burungale-Castella-Skinner 2024)")

