"""
Approach B: BF Partition Function Analysis

Park & Park (2602.19621) Proposition 6.5 gives the KEY formula:

    Z_X = |pi(Sel(M, W))| * |Sel(M_1^v, W_1^perp)|

For the case of an elliptic curve E/Q with the n-isogeny sequence
    0 -> E[phi] -> E[n*phi] -> E[n] -> 0
the partition function becomes:

    Z_X = |im(Sel_{phi}(E) -> Sel_n(E))| * |Sel_{phi^hat}(E')|

where phi: E -> E' is the isogeny and phi^hat is the dual.

KEY QUESTION: Does finiteness of Z_X IMPLY finiteness of Sha?
Or does Z_X's finiteness follow FROM Sha being finite?

ANALYSIS:
"""

print("="*80)
print("APPROACH B: BF PARTITION FUNCTION ANALYSIS")
print("="*80)

print("""
Park & Park Proposition 6.5 (the partition function formula):

    Z_X = |pi(Sel(M, W))| * |Sel(M_1^v, W_1^perp)|

For M = E[n] with the sequence 0 -> M_1 -> M -> M_2 -> 0:

    Z_X = |pi(Sel(M, W))| * |Sel(M_1^v, W_1^perp)|

Both factors are SELMER GROUP sizes, which are ALWAYS FINITE 
(by Remark 5.4, which cites Cesnavicius Theorem 3.2).

So Z_X is ALWAYS finite. This is automatic from:
  - Selmer groups are finite (proved by Cassels, 1960s)
  - The partition function is a product of two finite Selmer groups

CRUCIAL OBSERVATION:
  Z_X being finite does NOT prove Sha is finite!
  
  The relationship is:
    Sha[n] = ker(Sel_n(E) -> prod_v E(Q_v)/nE(Q_v))
           = Sel_n(E) / im(E(Q)/nE(Q))
  
  So |Sha[n]| = |Sel_n(E)| / |E(Q)/nE(Q)| (when these are all finite)
  
  |Sha[n]| = |Sel_n(E)| / n^rank * (torsion correction)
  
  But Z_X involves Sel(M, W) and Sel(M_1^v, W_1^perp), which are 
  DIFFERENT Selmer groups from Sel_n(E). Specifically:
  
  - Sel(M, W) is the Selmer group for the FULL module M = E[n]
    with the standard Selmer conditions W
  - Sel(M_1^v, W_1^perp) is the Selmer group for the DUAL module M_1^v
    with the ORTHOGONAL Selmer conditions
  
  Both are finite BY DEFINITION of Selmer groups.

DIRECTION OF IMPLICATION:
  Z_X finite <== Selmer groups finite (always true)
  
  NOT:
  Z_X finite ==> Sha finite
  
  The BF partition function is finite REGARDLESS of whether Sha is finite.
  The issue is that Sha = Sel/E(Q)/nE(Q), and while Sel is finite,
  E(Q)/nE(Q) is also finite (since E(Q) is finitely generated by Mordell-Weil).
  
  So Sha[n] is ALWAYS a quotient of two finite groups, hence finite.
  BUT: This is only Sha[n], the n-torsion. The FULL Sha is 
  the direct limit of Sha[n] over all n. Sha is finite iff 
  Sha[n] = Sha[n^2] for all sufficiently large n (i.e., stabilization).

THE REAL PROBLEM:
  We know: dim_Fp Sha[p^k] is finite for every fixed k.
  We want: Sha[p^infty] := union_k Sha[p^k] is finite.
  
  Equivalently: Sha[p^k] stabilizes as k -> infinity.
  
  The BF theory gives Z_{X,n} for each n. As n = p^k grows:
    Z_{X,p^k} = |pi(Sel_{p^k}(M, W))| * |Sel(M_1^v, W_1^perp)|
  
  Sha is finite iff the Selmer groups |Sel_{p^k}| grow like p^{2k*rank}
  (the E(Q)/p^k E(Q) part grows like p^{k*rank}, and Sha[p^k] stabilizes).
  
  If Sha[p^infty] is infinite, then |Sel_{p^k}| grows FASTER than p^{2k*rank}.
  
  Can the BF theory detect this? The partition function Z is a sum of phases:
    Z_X = sum_{rho in F(X)} exp(2*pi*i * BF_X(rho))
  
  If Sha is infinite, F(X) is still finite (for fixed n), but as n -> infty,
  |F(X)| = |Sel_n| grows. The BF theory would need to detect the GROWTH RATE
  of |Sel_{p^k}|, which relates to Iwasawa theory.

CONCLUSION FOR APPROACH B:
  The BF partition function Z_X is ALWAYS finite (a product of finite 
  Selmer groups). It does not provide new information about Sha finiteness.
  
  However, the GROWTH of Z_{X,p^k} as k -> infinity IS related to Sha 
  finiteness via Iwasawa theory. If Z_{X,p^k} ~ C * p^{2k*rank} as k -> inf,
  then Sha is finite. If it grows faster, Sha[p^infty] is infinite.
  
  The BF theory repackages the Iwasawa-theoretic question:
    Is the Iwasawa mu-invariant of E zero?
    (mu = 0 iff Sha[p^infty] is finite, for p of good ordinary reduction,
     assuming the Iwasawa main conjecture)
  
  Park & Park's contribution is a STRUCTURAL result (Cassels-Tate = BF 
  functional) not a FINITENESS result.
""")

print("="*80)
print("APPROACH C: QUANTUM CHANNEL CAPACITY")
print("="*80)

print("""
MODEL: The local-to-global map as a quantum channel.

Setup:
  - Input: H^1(G_S, E[p]) (global cohomology classes)
  - Output: prod_{v in S} H^1(Q_v, E[p]) (local cohomology)
  - Channel: The restriction map delta_S: H^1(G_S, E[p]) -> prod_v H^1(Q_v, E[p])
  - Selmer group = preimage of local conditions L_v under delta_S
  - Sha = kernel of delta_S restricted to Sel_p

The "noise" of this channel is determined by the local conditions:
  At each prime v, the noise is the probability that a random global class
  maps to a class satisfying the local Selmer condition at v.

For the quantum erasure channel with erasure probability epsilon:
  - Quantum capacity = max(0, 1 - 2*epsilon)  (for qubits)
  - For the CSS code: capacity = max(0, 1 - 2 * (fraction of checks failed))

The problem: The "noise model" for the arithmetic channel is NOT an 
independent erasure model. The primes are CORRELATED through the global 
Galois representation. The quantum capacity theorem assumes memoryless 
channels (or at least i.i.d. noise).

For the arithmetic setting:
  - The "noise" at different primes is correlated through the global 
    representation rho_{E,p}: G_Q -> GL_2(F_p)
  - The Chebotarev density theorem says that Frobenius elements at 
    different primes are equidistributed in the image of rho_{E,p},
    so they are asymptotically "independent" -- but only in density,
    not for finite S.

Attempt to apply capacity theorem:
  - Each prime v contributes a "check" of dimension dim H^1(Q_v, E[p])/L_v
  - Total check dimension = sum_v (dim H^1(Q_v, E[p]) - dim L_v)
  - The "code rate" R = dim Sha[p] / dim H^1(G_S, E[p])
  - Capacity bound: R <= 1 - (total check dimension / n)

From Poitou-Tate:
  n - dim Sel_p = dim(cokernel of restriction to prod L_v)
               = dim(prod H^1(Q_v)/L_v) - dim(image of dual Selmer)
               
  By self-duality of the Poitou-Tate sequence:
  dim Sel_p + dim Sel_p^dual = n + dim H^0 - dim H^2^dual + ...

The capacity bound gives:
  dim Sha[p] <= (1 - 1/p) * n  (self-dual CSS capacity)
  
This is exactly the same bound as Approach A. The quantum channel 
approach does NOT give a different bound -- it gives the CSS capacity 
bound from a different angle.

WHY: The CSS capacity bound IS the quantum channel capacity for a 
depolarizing channel with parameter p. The self-duality of the 
Cassels-Tate pairing (alternating + perfect) means the code is 
self-dual, which is exactly the condition for the CSS capacity bound 
to equal the channel capacity.

CONCLUSION FOR APPROACH C:
  The quantum channel approach gives the SAME bound as Approach A.
  It does not provide additional constraints beyond:
    dim Sha[p] <= (1 - 1/p) * dim H^1(G_S, E[p])
  
  This bound grows with the number of bad primes and cannot prove 
  uniform finiteness.
""")

print("="*80)
print("IDENTIFYING THE PRECISE GAP")
print("="*80)

print("""
THE GAP: Why the quantum framework CANNOT prove Sha finiteness
=========================================================

What "Sha finiteness" means:
  Sha(E/Q) is finite <=> for all primes p, Sha(E/Q)[p^infty] is finite
                     <=> for all p, there exists k such that Sha[p^k] = Sha[p^{k+1}]

What the quantum framework gives:
  For each FIXED prime p and exponent k:
    dim_Fp Sha[p^k] <= (1-1/p) * dim H^1(G_S, E[p^k])  ... (*)
  
  The RHS is finite for each fixed (p, k).

The gap:
  (*) gives a bound that depends on k. As k -> infinity:
    dim H^1(G_S, E[p^k]) can grow with k.
  
  We need: Sha[p^k] STABILIZES as k -> infinity.
  The bound (*) does NOT ensure stabilization.

Why this gap is fundamental:
  1. The CSS code is built from E[p] (or E[p^k]) for FIXED torsion.
     Each p gives a different code. The code for E[p] knows nothing about E[p^2].
     
  2. Sha finiteness is about the p-adic Selmer group Sel_{p^infty}(E) 
     being cofinitely generated -- this is an IWASAWA-THEORETIC property.
     
  3. The CSS/BF framework operates at a FIXED level (mod p^k).
     It does not capture the p-adic tower structure.

What WOULD be needed:
  To prove Sha finiteness from quantum information theory, one would need
  either:
  
  (a) A FAMILY of CSS codes {C_k}_{k >= 1} (one for each E[p^k]) with
      a compatibility condition ensuring that the logical spaces stabilize.
      This would be a "p-adic CSS code" -- a projective system of codes.
      
  (b) A single code built from the FULL p-adic Tate module T_p(E),
      not just the finite torsion E[p^k]. The Selmer group of T_p(E) is
      the Selmer group studied in Iwasawa theory.
      
  (c) A connection between the BF partition function's p-adic behavior
      (Z_{X,p^k} as a function of k) and the Iwasawa mu-invariant.
      mu = 0 <=> Sha[p^infty] finite (under standard hypotheses).

Specifically:
  - Kato (2004) proved: If L(E,1) != 0, then Sha(E/Q) is finite.
    This uses the Euler system for T_p(E), which is a p-adic object.
    
  - Kolyvagin (1990) proved: If rank_an(E) = 1, then Sha is finite.
    This uses an Euler system of Heegner points in the p-adic tower.
    
  - For rank >= 2: No Euler system is known. The quantum framework 
    does not provide one.

The CSS/BF framework provides:
  1. A structural dictionary (Sha = logical qubits, rank = stabilizers)
  2. A non-trivial bound at each fixed level (CSS capacity)
  3. A connection to topology (BF = Cassels-Tate pairing)
  
It does NOT provide:
  1. p-adic compatibility (tower structure)
  2. An Euler system
  3. A proof of mu = 0
  4. Any information about the rank >= 2 case that isn't already known

POSSIBLE NEW DIRECTIONS:
  1. Build a "p-adic CSS code" from the projective system E[p^k] and 
     study when the logical space stabilizes.
     
  2. Use the BF theory to construct an EULER SYSTEM. The BF partition 
     function Z_{X,p^k} is related to p-adic L-values. If one could 
     show Z_{X,p^k} satisfies an Euler system norm relation, this would
     give Sha finiteness via Kolyvagin's method.
     
  3. Use the entanglement entropy of the arithmetic BF theory (reference [4]
     in Park & Park: Chung-Kim-Kim-Kim-Park-Yoo 2024) to detect mu = 0.
     The mu-invariant controls growth of Sha in the cyclotomic tower.
     Entropy growth ~ mu.
""")
