"""
Step 5: Search for curves with non-trivial Sha (|Sha| > 1)
and test whether TDA persistence features detect it.

Sha(E) is the CORE arithmetic object in BSD. If persistent homology
detects Sha, that would be a genuine breakthrough connecting
computational topology to arithmetic geometry.
"""


# This file was *autogenerated* from the file scripts/05_sha_detection.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_53 = Integer(53); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_16 = Integer(16); _sage_const_25 = Integer(25); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_500 = Integer(500); _sage_const_15000 = Integer(15000); _sage_const_50 = Integer(50); _sage_const_5000 = Integer(5000); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_10 = Integer(10); _sage_const_60 = Integer(60); _sage_const_2 = Integer(2)
import json
import os

OUTPUT_DIR = "/Users/seanross/kingdom_of_god/home-base/research_hub/big-thinkers/research-systems/bsd-conjecture/approach-3-tda/data"
NUM_PRIMES = _sage_const_100 
prime_list = primes_first_n(NUM_PRIMES)

class SageEncoder(json.JSONEncoder):
    def default(self, obj):
        try:
            return int(obj)
        except (TypeError, ValueError):
            pass
        try:
            return float(obj)
        except (TypeError, ValueError):
            pass
        return super().default(obj)

def curve_data_full(E, label=None):
    """Extract full arithmetic data."""
    try:
        r = int(E.rank())
        N = int(E.conductor())
        if label is None:
            label = str(E.cremona_label())

        try:
            sha_an = float(E.sha().an_numerical(prec=_sage_const_53 ))
        except:
            sha_an = None

        torsion = int(E.torsion_order())
        ap_values = [int(E.ap(p)) for p in prime_list]

        red_types = []
        for p in prime_list:
            if N % int(p) != _sage_const_0 :
                red_types.append(_sage_const_0 )
            else:
                try:
                    Ep = E.local_data(p)
                    rt = Ep.bad_reduction_type()
                    red_types.append(int(rt) if rt is not None else _sage_const_0 )
                except:
                    red_types.append(_sage_const_0 )

        tamagawa = int(E.tamagawa_product())

        return {
            'label': str(label),
            'rank': r,
            'conductor': N,
            'sha_an': sha_an,
            'sha_an_rounded': int(round(sha_an)) if sha_an is not None else None,
            'torsion': torsion,
            'tamagawa': tamagawa,
            'ap': ap_values,
            'reduction_types': red_types,
        }
    except Exception as e:
        print(f"  FAILED: {e}")
        return None


# =====================================================================
# Strategy: find curves with |Sha| = 4, 9, 16, 25, etc.
# These exist but are rarer at low conductor.
# =====================================================================

print("=== Searching for curves with non-trivial Sha ===")

sha_curves = []
sha_counts = {}

# Known curves with non-trivial Sha:
known_sha_curves = [
    # Sha = 4
    ('571a1', _sage_const_4 ),
    ('681b1', _sage_const_4 ),
    ('960d1', _sage_const_4 ),
    ('1058d1', _sage_const_4 ),
    ('1070a1', _sage_const_4 ),
    ('1246b1', _sage_const_4 ),
    ('1913b1', _sage_const_4 ),
    ('2006e1', _sage_const_4 ),
    ('2429b1', _sage_const_4 ),
    ('2534e1', _sage_const_4 ),
    ('2541d1', _sage_const_4 ),
    ('2674b1', _sage_const_4 ),
    ('2710b1', _sage_const_4 ),
    ('2768c1', _sage_const_4 ),
    ('2849a1', _sage_const_4 ),
    ('2932a1', _sage_const_4 ),
    ('3054a1', _sage_const_4 ),
    ('3306b1', _sage_const_4 ),
    ('3536h1', _sage_const_4 ),
    ('3712j1', _sage_const_4 ),
    # Sha = 9
    ('5765a1', _sage_const_9 ),
    ('7390a1', _sage_const_9 ),
    ('8270a1', _sage_const_9 ),
    ('11310a1', _sage_const_9 ),
    # Sha = 16
    ('9834c1', _sage_const_16 ),
    ('12846a1', _sage_const_16 ),
    # Sha = 25
    ('67890a1', _sage_const_25 ),
]

# Also search systematically
print("Checking known Sha > 1 curves...")
for label, expected_sha in known_sha_curves:
    try:
        E = EllipticCurve(label)
        data = curve_data_full(E, label)
        if data is not None and data['sha_an'] is not None:
            sha_round = int(round(data['sha_an']))
            if sha_round > _sage_const_1 :
                sha_curves.append(data)
                sha_counts[sha_round] = sha_counts.get(sha_round, _sage_const_0 ) + _sage_const_1 
                if len(sha_curves) % _sage_const_5  == _sage_const_0 :
                    print(f"  Found {len(sha_curves)} curves with Sha > 1")
    except Exception as e:
        pass

# Systematic search
print("\nSystematic search for Sha > 1 in Cremona database...")
for N in range(_sage_const_500 , _sage_const_15000 ):
    if len(sha_curves) >= _sage_const_50 :
        break
    try:
        for E in cremona_optimal_curves(N):
            try:
                r = int(E.rank())
                if r == _sage_const_0 :  # Sha is most interesting for rank 0
                    sha_val = float(E.sha().an_numerical(prec=_sage_const_53 ))
                    sha_round = int(round(sha_val))
                    if sha_round > _sage_const_1 :
                        data = curve_data_full(E)
                        if data is not None:
                            sha_curves.append(data)
                            sha_counts[sha_round] = sha_counts.get(sha_round, _sage_const_0 ) + _sage_const_1 
                            print(f"  Found Sha={sha_round}: {data['label']} (conductor={N})")
            except:
                continue
    except:
        continue

print(f"\nTotal Sha > 1 curves: {len(sha_curves)}")
print(f"Sha distribution: {sha_counts}")

# Also get matching Sha=1 curves (same conductor range) as control
print("\nCollecting Sha=1 control curves...")
sha1_curves = []
sha_conductors = [c['conductor'] for c in sha_curves]
for N in range(min(sha_conductors) if sha_conductors else _sage_const_500 ,
               max(sha_conductors) + _sage_const_100  if sha_conductors else _sage_const_5000 ):
    if len(sha1_curves) >= len(sha_curves):
        break
    try:
        for E in cremona_optimal_curves(N):
            try:
                r = int(E.rank())
                if r == _sage_const_0 :
                    sha_val = float(E.sha().an_numerical(prec=_sage_const_53 ))
                    if abs(sha_val - _sage_const_1p0 ) < _sage_const_0p1 :
                        data = curve_data_full(E)
                        if data is not None:
                            sha1_curves.append(data)
                            if len(sha1_curves) % _sage_const_10  == _sage_const_0 :
                                print(f"  {len(sha1_curves)} control curves")
                            if len(sha1_curves) >= max(_sage_const_60 , len(sha_curves)):
                                break
            except:
                continue
    except:
        continue
    if len(sha1_curves) >= max(_sage_const_60 , len(sha_curves)):
        break

print(f"Control (Sha=1) curves: {len(sha1_curves)}")

# Save
all_sha_data = {
    'sha_nontrivial': sha_curves,
    'sha_trivial': sha1_curves,
    'prime_list': [int(p) for p in prime_list],
    'num_primes': int(NUM_PRIMES),
}

outpath = os.path.join(OUTPUT_DIR, "sha_detection_data.json")
indent_val = int(Integer(_sage_const_2 ))
with open(outpath, 'w') as f:
    json.dump(all_sha_data, f, indent=indent_val, cls=SageEncoder)

print(f"\nSaved to {outpath}")

