"""
Maximum precision verification: 389a1 at p=5, push n_terms as high as feasible.
We want to confirm that ratio = 1 to many digits.
"""


# This file was *autogenerated* from the file verify_max_prec.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_30 = Integer(30); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12)
import time

E = EllipticCurve('389a1')
print(f"E = 389a1, rank {E.rank()}", flush=True)

p = _sage_const_5 
PREC = _sage_const_30 

K = Qp(p, PREC)
R = PolynomialRing(K, names=('x',)); (x,) = R._first_ngens(1)
alpha = (x**_sage_const_2  - E.ap(p)*x + p).roots(multiplicities=False)
alpha = [r for r in alpha if r.valuation() == _sage_const_0 ][_sage_const_0 ]
fac = (_sage_const_1  - _sage_const_1 /alpha)**_sage_const_2 
log_g = K(_sage_const_1 +p).log()

print(f"computing Reg_p at prec {PREC}...", flush=True)
t0 = time.time()
Reg_p = E.padic_regulator(p, PREC)
print(f"  done in {time.time()-t0:.1f}s, Reg_p = {Reg_p}", flush=True)

rhs = fac * Reg_p / log_g**_sage_const_2 
print(f"  predicted (high-prec) RHS = {rhs}", flush=True)

# Push n higher and higher
for n in [_sage_const_8 , _sage_const_10 , _sage_const_12 ]:
    print(f"\n--- n_terms = {n} ---", flush=True)
    Lp = E.padic_lseries(p)
    t0 = time.time()
    try:
        Lps = Lp.series(n=n, prec=PREC)
        elapsed = time.time() - t0
        print(f"  series done in {elapsed:.1f}s", flush=True)
        coeffs = Lps.list()
        leading = coeffs[_sage_const_2 ]
        print(f"  L_p^(2)/2! = {leading}", flush=True)
        print(f"  abs prec = {leading.precision_absolute()}", flush=True)
        diff = leading - rhs
        print(f"  difference = {diff}", flush=True)
        ratio = leading / rhs
        print(f"  ratio = {ratio}", flush=True)
        print(f"  val(ratio - 1) = {(ratio - _sage_const_1 ).valuation()}", flush=True)
    except Exception as e:
        print(f"  ERROR: {e}", flush=True)
        break

