"""
Compute Frobenius moment statistics and Selmer group data for elliptic curves.

Goal: Test whether the first k moments of {a_p/p} jointly determine (rank, dim Sha[p]).

For each curve we compute:
  - Mordell-Weil rank
  - 2-Selmer rank (dim_F2 Sel_2(E))
  - Analytic Sha (from BSD formula)
  - Frobenius trace moments: M_k = sum_{p<=X} a_p^k / p^k for k=1,2,3,4
  - Weighted moments: W_k = sum_{p<=X} a_p^k / p^{k/2+1} (Sato-Tate normalized)
  - The symmetric square partial sum: sum_{p<=X} (a_p^2 - p) / p^2
  - Murmuration sum: sum a_p * p^{-0.84}
"""


# This file was *autogenerated* from the file compute_moment_selmer.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5000 = Integer(5000); _sage_const_500 = Integer(500); _sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1p0 = RealNumber('1.0'); _sage_const_50 = Integer(50); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p5 = RealNumber('0.5'); _sage_const_23 = Integer(23); _sage_const_0p84 = RealNumber('0.84'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_1p5 = RealNumber('1.5')
import json
import sys
from collections import defaultdict

# Parameters
MAX_CONDUCTOR = _sage_const_5000 
PRIME_BOUND = _sage_const_500 
NUM_PRIMES = _sage_const_100   # first 100 primes

# Get primes
primes_list = list(primes(PRIME_BOUND + _sage_const_1 ))[:NUM_PRIMES]
print(f"Using {len(primes_list)} primes up to {primes_list[-_sage_const_1 ]}")

# Collect data
results = []
db = CremonaDatabase()

conductors = range(_sage_const_1 , MAX_CONDUCTOR + _sage_const_1 )
count = _sage_const_0 
errors = _sage_const_0 

for N in conductors:
    try:
        curves = db.allcurves(N)
    except Exception:
        continue

    for label_suffix, data in curves.items():
        label = f"{N}{label_suffix}"
        try:
            ainvs = data[_sage_const_0 ] if isinstance(data, (list, tuple)) else data
            E = EllipticCurve(ainvs)

            # Basic invariants
            rank = E.rank()
            conductor = E.conductor()
            torsion_order = E.torsion_order()
            torsion_struct = [int(x) for x in E.torsion_subgroup().invariants()]

            # 2-Selmer group
            try:
                sel2 = E.selmer_rank()  # This is dim_F2(Sel_2)
            except Exception:
                sel2 = -_sage_const_1 

            # Analytic Sha
            try:
                sha_an = E.sha().an()
                sha_val = float(sha_an)
            except Exception:
                sha_val = -_sage_const_1p0 

            # Frobenius traces at good primes
            ap_list = []
            good_primes = []
            for p in primes_list:
                if conductor % p != _sage_const_0 :
                    ap = int(E.ap(p))
                    ap_list.append(ap)
                    good_primes.append(int(p))

            if len(ap_list) < _sage_const_50 :
                continue

            # Compute moments
            # M_k = sum a_p^k / p^k (the raw moments)
            M1 = sum(a / float(p) for a, p in zip(ap_list, good_primes))
            M2 = sum(a**_sage_const_2  / float(p)**_sage_const_2  for a, p in zip(ap_list, good_primes))
            M3 = sum(a**_sage_const_3  / float(p)**_sage_const_3  for a, p in zip(ap_list, good_primes))
            M4 = sum(a**_sage_const_4  / float(p)**_sage_const_4  for a, p in zip(ap_list, good_primes))

            # Sato-Tate normalized moments: a_p / (2*sqrt(p))
            # W_k = sum (a_p/(2*sqrt(p)))^k / p  (normalized by 1/p for convergence)
            W1 = sum(a / (_sage_const_2  * float(p)**_sage_const_0p5 ) / float(p) for a, p in zip(ap_list, good_primes))
            W2 = sum((a / (_sage_const_2  * float(p)**_sage_const_0p5 ))**_sage_const_2  / float(p) for a, p in zip(ap_list, good_primes))
            W3 = sum((a / (_sage_const_2  * float(p)**_sage_const_0p5 ))**_sage_const_3  / float(p) for a, p in zip(ap_list, good_primes))
            W4 = sum((a / (_sage_const_2  * float(p)**_sage_const_0p5 ))**_sage_const_4  / float(p) for a, p in zip(ap_list, good_primes))

            # Second moment deviation: sum (a_p^2 - p) / p^2
            sym2_sum = sum((a**_sage_const_2  - float(p)) / float(p)**_sage_const_2  for a, p in zip(ap_list, good_primes))

            # E[a_p^2]/p for small primes (p <= 23)
            small_primes_ap2 = []
            for a, p in zip(ap_list, good_primes):
                if p <= _sage_const_23 :
                    small_primes_ap2.append(a**_sage_const_2  / float(p))
            mean_ap2_over_p_small = sum(small_primes_ap2) / len(small_primes_ap2) if small_primes_ap2 else _sage_const_0 

            # Murmuration sum: sum a_p * p^{-0.84}
            murm_sum = sum(a * float(p)**(-_sage_const_0p84 ) for a, p in zip(ap_list, good_primes))

            # Running coupling at Lambda
            # g(Lambda) = log|L_Lambda(E,1)| / log(Lambda)
            # L_Lambda = prod (1 - a_p/p + 1/p)^{-1}
            log_L = _sage_const_0p0 
            for a, p in zip(ap_list, good_primes):
                euler_factor = _sage_const_1p0  - float(a)/float(p) + _sage_const_1p0 /float(p)
                if euler_factor > _sage_const_0 :
                    log_L -= log(euler_factor)
                else:
                    log_L -= log(abs(euler_factor))

            Lambda = good_primes[-_sage_const_1 ]
            g_Lambda = log_L / log(float(Lambda))

            # Local data: frequency of a_p ≡ 0 mod 2
            freq_ap_even = sum(_sage_const_1  for a in ap_list if a % _sage_const_2  == _sage_const_0 ) / len(ap_list)

            # Average |a_p|/sqrt(p) (Sato-Tate scale)
            mean_normalized_ap = sum(abs(a) / float(p)**_sage_const_0p5  for a, p in zip(ap_list, good_primes)) / len(ap_list)

            entry = {
                'label': label,
                'conductor': int(conductor),
                'rank': int(rank),
                'sel2_rank': int(sel2),  # dim_F2(Sel_2(E))
                'sha_an': round(sha_val, _sage_const_6 ),
                'torsion_order': int(torsion_order),
                'torsion_struct': torsion_struct,
                'M1': round(M1, _sage_const_8 ),
                'M2': round(M2, _sage_const_8 ),
                'M3': round(M3, _sage_const_8 ),
                'M4': round(M4, _sage_const_8 ),
                'W1': round(W1, _sage_const_8 ),
                'W2': round(W2, _sage_const_8 ),
                'W3': round(W3, _sage_const_8 ),
                'W4': round(W4, _sage_const_8 ),
                'sym2_sum': round(sym2_sum, _sage_const_8 ),
                'mean_ap2_over_p_small': round(mean_ap2_over_p_small, _sage_const_6 ),
                'murm_sum': round(murm_sum, _sage_const_6 ),
                'g_Lambda': round(g_Lambda, _sage_const_8 ),
                'freq_ap_even': round(freq_ap_even, _sage_const_6 ),
                'mean_normalized_ap': round(mean_normalized_ap, _sage_const_6 ),
                'n_good_primes': len(ap_list),
            }
            results.append(entry)
            count += _sage_const_1 

            if count % _sage_const_500  == _sage_const_0 :
                print(f"  Processed {count} curves (conductor <= {N})")

        except Exception as e:
            errors += _sage_const_1 
            if errors <= _sage_const_10 :
                print(f"  Error on {label}: {e}")

print(f"\nDone: {count} curves processed, {errors} errors")
print(f"Rank distribution: {dict(sorted(defaultdict(int, {r: sum(_sage_const_1  for e in results if e['rank']==r) for r in set(e['rank'] for e in results)}).items()))}")
print(f"Sel2 distribution: {dict(sorted(defaultdict(int, {s: sum(_sage_const_1  for e in results if e['sel2_rank']==s) for s in set(e['sel2_rank'] for e in results)}).items()))}")

# Count curves with non-trivial Sha
sha_nontrivial = [e for e in results if e['sha_an'] > _sage_const_1p5 ]
print(f"Curves with |Sha| > 1: {len(sha_nontrivial)}")
sha_counts = defaultdict(int)
for e in sha_nontrivial:
    sha_counts[round(e['sha_an'])] += _sage_const_1 
print(f"  Sha value distribution: {dict(sorted(sha_counts.items()))}")

# Save
output_path = "/Users/seanross/kingdom_of_god/home-base/research_hub/big-thinkers/research-systems/bsd-conjecture/bridge-a-selmer-corank/moment_selmer_data.json"
with open(output_path, 'w') as f:
    json.dump(results, f, indent=_sage_const_1 )
print(f"Saved to {output_path}")

