"""
End-to-end test of the corank bridge on a fresh set of curves.

The bridge chain:
  1. Compute a_p for primes up to X
  2. M1 = sum a_p/p -> rank (via explicit formula rounding)
  3. freq_ap_even -> tors2_rk
  4. sel2_rank (algebraic) -> sha2_dim = sel2 - rank - tors2_rk

Test: how accurately does this chain recover rank and sha2_dim?
"""


# This file was *autogenerated* from the file test_bridge_end_to_end.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_50 = Integer(50); _sage_const_300 = Integer(300); _sage_const_1 = Integer(1); _sage_const_0p55 = RealNumber('0.55'); _sage_const_1p65 = RealNumber('1.65'); _sage_const_5001 = Integer(5001); _sage_const_8001 = Integer(8001); _sage_const_2 = Integer(2); _sage_const_30 = Integer(30); _sage_const_4 = Integer(4); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p99 = RealNumber('0.99'); _sage_const_500 = Integer(500); _sage_const_60 = Integer(60)
import json
from collections import Counter, defaultdict
from math import log

db = CremonaDatabase()

# Test curves: conductor 5001-8000 (NOT in training set)
correct_rank = _sage_const_0 
correct_sha2 = _sage_const_0 
total = _sage_const_0 
rank_errors_by_true_rank = defaultdict(int)
rank_correct_by_true_rank = defaultdict(int)

NUM_PRIMES = _sage_const_50 
primes_list = list(primes(_sage_const_300 ))[:NUM_PRIMES]
X = int(primes_list[-_sage_const_1 ])
log_log_X = log(log(X))

# Calibration from training data:
# M1_mean(rank=0) ≈ +0.55 (50 primes), M1_mean(rank=1) ≈ -1.1
# Spacing ≈ 1.65 per rank unit
# Threshold: rank = round((-M1 + C_base) / spacing)
# where C_base ≈ 0.55 (mean C(E) at rank 0)
C_base = _sage_const_0p55 
spacing = _sage_const_1p65   # slightly larger than log_log_X due to the 15% excess

tested = _sage_const_0 
for N in range(_sage_const_5001 , _sage_const_8001 ):
    try:
        curves = db.allcurves(N)
    except:
        continue
    for label_suffix, data_raw in curves.items():
        label = f"{N}{label_suffix}"
        try:
            ainvs = data_raw[_sage_const_0 ] if isinstance(data_raw, (list, tuple)) else data_raw
            E = EllipticCurve(ainvs)

            true_rank = E.rank()
            true_sel2 = E.selmer_rank()
            true_sha = round(float(E.sha().an()))
            tors = [int(x) for x in E.torsion_subgroup().invariants()]
            true_tors2 = sum(_sage_const_1  for t in tors if t % _sage_const_2  == _sage_const_0 )
            true_sha2_dim = true_sel2 - true_rank - true_tors2

            # Compute a_p
            good_ap = []
            for p in primes_list:
                if N % int(p) != _sage_const_0 :
                    good_ap.append((int(p), int(E.ap(p))))

            if len(good_ap) < _sage_const_30 :
                continue

            # Step 1: Compute M1
            M1 = sum(a/float(p) for p, a in good_ap)

            # Step 2: Infer rank from M1
            rank_est = max(_sage_const_0 , round((-M1 + C_base) / spacing))
            rank_est = min(rank_est, _sage_const_4 )  # cap at 4

            # Step 3: Infer tors2_rk from freq_ap_even
            freq_even = sum(_sage_const_1  for p, a in good_ap if p > _sage_const_2  and a % _sage_const_2  == _sage_const_0 ) / sum(_sage_const_1  for p, _ in good_ap if p > _sage_const_2 )
            tors2_est = _sage_const_0  if freq_even < _sage_const_0p9  else _sage_const_1 
            # Distinguish tors2=1 from tors2=2
            if freq_even > _sage_const_0p99 :
                # Could be tors2=2, but need more info
                # For now, use torsion order if available from a_p data
                # Actually, can detect Z/2 x Z/2 vs Z/2 from the a_p pattern
                # Z/2 x Z/2 means all a_p ≡ 0 mod 4 for good p ≡ 1 mod 4? No.
                # Just use freq > 0.99 as indicator of 2-rank >= 1
                tors2_est = _sage_const_1 

            # Step 4: Compute sha2_dim
            sha2_est = max(_sage_const_0 , true_sel2 - rank_est - tors2_est)

            if true_rank == rank_est:
                correct_rank += _sage_const_1 
                rank_correct_by_true_rank[true_rank] += _sage_const_1 
            else:
                rank_errors_by_true_rank[true_rank] += _sage_const_1 

            if true_sha2_dim == sha2_est:
                correct_sha2 += _sage_const_1 

            total += _sage_const_1 

        except Exception:
            pass

    if N % _sage_const_500  == _sage_const_0 :
        if total > _sage_const_0 :
            print(f"N<={N}: {total} curves, rank acc={correct_rank/total:.3f}, sha2 acc={correct_sha2/total:.3f}")

print(f"\n{'='*_sage_const_60 }")
print(f"END-TO-END BRIDGE TEST (conductor 5001-8000)")
print(f"{'='*_sage_const_60 }")
print(f"Total curves: {total}")
print(f"Rank accuracy: {correct_rank}/{total} = {correct_rank/total:.3f}" if total else "No curves")
print(f"sha2_dim accuracy: {correct_sha2}/{total} = {correct_sha2/total:.3f}" if total else "No curves")

print(f"\nRank accuracy by true rank:")
for r in sorted(set(list(rank_correct_by_true_rank.keys()) + list(rank_errors_by_true_rank.keys()))):
    correct = rank_correct_by_true_rank[r]
    errors = rank_errors_by_true_rank[r]
    total_r = correct + errors
    print(f"  rank={r}: {correct}/{total_r} = {correct/total_r:.3f}" if total_r > _sage_const_0  else f"  rank={r}: 0/0")

