"""
Fast test: rank extraction from M1 only (skip selmer_rank computation).
Tests on 2000 curves from conductor 3001-5000.
"""


# This file was *autogenerated* from the file test_rank_extraction.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_50 = Integer(50); _sage_const_300 = Integer(300); _sage_const_1 = Integer(1); _sage_const_0p55 = RealNumber('0.55'); _sage_const_1p65 = RealNumber('1.65'); _sage_const_3001 = Integer(3001); _sage_const_5001 = Integer(5001); _sage_const_30 = Integer(30); _sage_const_4 = Integer(4); _sage_const_500 = Integer(500); _sage_const_60 = Integer(60); _sage_const_2 = Integer(2); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p27 = RealNumber('0.27'); _sage_const_0p62 = RealNumber('0.62'); _sage_const_0p95 = RealNumber('0.95'); _sage_const_3 = Integer(3)
from collections import Counter, defaultdict
from math import log

db = CremonaDatabase()

correct_rank = _sage_const_0 
total = _sage_const_0 
rank_by_true = defaultdict(list)

NUM_PRIMES = _sage_const_50 
primes_list = list(primes(_sage_const_300 ))[:NUM_PRIMES]
X = int(primes_list[-_sage_const_1 ])
log_log_X = log(log(X))

# From earlier analysis: spacing ~ 1.65, C_base ~ 0.55
C_base = _sage_const_0p55 
spacing = _sage_const_1p65 

for N in range(_sage_const_3001 , _sage_const_5001 ):
    try:
        curves = db.allcurves(N)
    except:
        continue
    for label_suffix, data_raw in curves.items():
        label = f"{N}{label_suffix}"
        try:
            ainvs = data_raw[_sage_const_0 ] if isinstance(data_raw, (list, tuple)) else data_raw
            E = EllipticCurve(ainvs)

            true_rank = E.rank()

            # Compute a_p
            good_ap = []
            for p in primes_list:
                if N % int(p) != _sage_const_0 :
                    good_ap.append((int(p), int(E.ap(p))))

            if len(good_ap) < _sage_const_30 :
                continue

            M1 = sum(a/float(p) for p, a in good_ap)
            rank_est = max(_sage_const_0 , round((-M1 + C_base) / spacing))
            rank_est = min(rank_est, _sage_const_4 )

            rank_by_true[true_rank].append((M1, rank_est == true_rank))

            if true_rank == rank_est:
                correct_rank += _sage_const_1 
            total += _sage_const_1 

        except Exception:
            pass

    if N % _sage_const_500  == _sage_const_0 :
        if total > _sage_const_0 :
            print(f"N<={N}: {total} curves, rank acc={float(correct_rank)/float(total):.3f}")

print(f"\n{'='*_sage_const_60 }")
print(f"RANK EXTRACTION TEST (conductor 3001-5000, 50 primes)")
print(f"{'='*_sage_const_60 }")
print(f"Total curves: {total}")
print(f"Overall rank accuracy: {correct_rank}/{total} = {float(correct_rank)/float(total):.3f}")

for r in sorted(rank_by_true.keys()):
    entries = rank_by_true[r]
    n = len(entries)
    correct = sum(_sage_const_1  for _, c in entries if c)
    m1_vals = [float(m) for m, _ in entries]
    mean_m1 = sum(m1_vals) / n
    std_m1 = (sum((x - mean_m1)**_sage_const_2  for x in m1_vals) / n)**_sage_const_0p5 
    print(f"  rank={r}: n={n}, acc={correct}/{n}={float(correct)/float(n):.3f}, M1={mean_m1:+.4f}+/-{std_m1:.4f}")

# Also test g_Lambda
print(f"\nWith running coupling (g_Lambda thresholds):")
correct_gL = _sage_const_0 
for N in range(_sage_const_3001 , _sage_const_5001 ):
    try:
        curves = db.allcurves(N)
    except:
        continue
    for label_suffix, data_raw in curves.items():
        try:
            ainvs = data_raw[_sage_const_0 ] if isinstance(data_raw, (list, tuple)) else data_raw
            E = EllipticCurve(ainvs)
            true_rank = E.rank()

            good_ap = []
            for p in primes_list:
                if N % int(p) != _sage_const_0 :
                    good_ap.append((int(p), int(E.ap(p))))
            if len(good_ap) < _sage_const_30 :
                continue

            log_L = _sage_const_0p0 
            for p, a in good_ap:
                ef = _sage_const_1p0  - float(a)/float(p) + _sage_const_1p0 /float(p)
                if ef > _sage_const_0 :
                    log_L -= log(ef)
                else:
                    log_L -= log(abs(ef))
            gL = log_L / log(float(good_ap[-_sage_const_1 ][_sage_const_0 ]))

            if gL > -_sage_const_0p27 :
                rank_est = _sage_const_0 
            elif gL > -_sage_const_0p62 :
                rank_est = _sage_const_1 
            elif gL > -_sage_const_0p95 :
                rank_est = _sage_const_2 
            else:
                rank_est = _sage_const_3 

            if true_rank == rank_est:
                correct_gL += _sage_const_1 
        except:
            pass

print(f"  g_Lambda accuracy: {correct_gL}/{total} = {float(correct_gL)/float(total):.3f}")

