#!/usr/bin/env sage
"""
Test the critical connection: lambda_p = rank iff Sha[p^infty] is finite.

For curves with known nontrivial Sha, check whether lambda_p > rank
(which would indicate Sha[p^infty] contributes to the lambda invariant).

Key theory:
- lambda >= rank always (Kato, Skinner-Urban)
- lambda = rank + dim(Sha[p^infty]) in many cases
- More precisely: lambda = corank_Zp(Sel_p^infty) = rank + corank_Zp(Sha[p^infty])
- Sha[p^infty] finite iff corank_Zp(Sha[p^infty]) = 0 iff lambda = rank

For KNOWN curves with nontrivial Sha:
- Sha is always finite (no known counterexamples)
- So Sha[p^infty] should be finite for all p
- Hence lambda_p should equal rank for all ordinary p
"""


# This file was *autogenerated* from the file compute_sha_lambda.sage
from sage.all_cmdline import *   # import sage library

_sage_const_80 = Integer(80); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_25 = Integer(25); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_70 = Integer(70); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_100p0 = RealNumber('100.0'); _sage_const_2 = Integer(2)
print("=" * _sage_const_80 )
print("SHA-LAMBDA CONNECTION TEST")
print("=" * _sage_const_80 )
print()
print("Theory: lambda_p = rank(E) + corank(Sha[p^infty])")
print("        Sha[p^infty] finite <==> lambda_p = rank(E)")
print()

# Curves with nontrivial Sha from the Cremona database
sha_curves = [
    # (label, rank, |Sha|, Sha_structure)
    ("571a1", _sage_const_0 , _sage_const_4 , "C2 x C2"),
    ("681b1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("960d1", _sage_const_0 , _sage_const_4 , "C2 x C2"),
    ("1058d1", _sage_const_0 , _sage_const_4 , "C2 x C2"),
    ("1073a1", _sage_const_0 , _sage_const_4 , "C2 x C2"),
    ("1246b1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("1483a1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("1613a1", _sage_const_0 , _sage_const_4 , "C2 x C2"),
    ("2006e1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("2366d1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("2834d1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("3054a1", _sage_const_0 , _sage_const_4 , "C2 x C2"),
    ("3364c1", _sage_const_0 , _sage_const_9 , "C3 x C3"),
    ("4229a1", _sage_const_0 , _sage_const_25 , "C5 x C5"),
    # Rank 1 curves with Sha (rare but exist)
    # Actually for rank <=1, Sha finiteness is proved by Kolyvagin.
    # The interesting case would be rank >=2 with nontrivial Sha, but these are rare.
]

test_primes = [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 , _sage_const_31 , _sage_const_37 , _sage_const_41 , _sage_const_43 , _sage_const_47 ]

print("{:<12} {:<5} {:<8} {:<12} {:<6} {:<8} {:<12}".format(
    "Curve", "Rank", "|Sha|", "Sha_struct", "p", "lambda", "lambda=rank?"
))
print("-" * _sage_const_70 )

all_results = []

for label, exp_rank, sha_order, sha_struct in sha_curves:
    try:
        E = EllipticCurve(label)
        rank = E.rank()
    except Exception:
        continue

    for p in test_primes:
        if E.conductor() % p == _sage_const_0 :
            continue
        if not E.is_ordinary(p):
            continue

        try:
            Lp = E.padic_lseries(p)
            n_terms = _sage_const_6 
            series = Lp.series(n=n_terms)

            lam = None
            for i in range(n_terms):
                coeff = series[i]
                if coeff.valuation() < coeff.precision_absolute():
                    lam = i
                    break

            if lam is not None:
                match = "YES" if lam == rank else "NO (lambda={})".format(lam)
                all_results.append((label, rank, sha_order, p, lam, lam == rank))
                print("{:<12} {:<5} {:<8} {:<12} {:<6} {:<8} {}".format(
                    label, rank, sha_order, sha_struct, p, lam, match
                ))
        except Exception:
            pass

print()
print("=" * _sage_const_80 )
print("SUMMARY FOR CURVES WITH NONTRIVIAL SHA")
print("=" * _sage_const_80 )

total = len(all_results)
matches = sum(_sage_const_1  for r in all_results if r[_sage_const_5 ])
print("Total (curve, prime) pairs tested: {}".format(total))
print("lambda = rank (Sha[p^infty] appears finite): {} ({:.1f}%)".format(
    matches, _sage_const_100p0  * matches / total if total > _sage_const_0  else _sage_const_0 ))
mismatches = [(r[_sage_const_0 ], r[_sage_const_2 ], r[_sage_const_3 ], r[_sage_const_4 ]) for r in all_results if not r[_sage_const_5 ]]
if mismatches:
    print()
    print("MISMATCHES (lambda != rank):")
    for label, sha, p, lam in mismatches:
        print("  {} (|Sha|={}): p={}, lambda={}".format(label, sha, p, lam))
        # Check if p divides |Sha|
        if sha % p == _sage_const_0 :
            print("    NOTE: p | |Sha| -- this is expected! Sha[p] nontrivial.")
            print("    BUT lambda should still = rank if Sha[p^infty] is FINITE.")
else:
    print()
    print("ALL MATCH: lambda_p = rank for every ordinary prime tested.")
    print("This is consistent with Sha[p^infty] being finite for all p.")
    print()
    print("KEY IMPLICATION: For these curves, the tower growth rate of Z_BF")
    print("determines rank(E(Q)) WITHOUT assuming Sha finiteness --")
    print("because the growth rate IS the lambda invariant, and lambda = rank")
    print("is a COMPUTATIONAL FACT for these curves, not an assumption.")

# Special analysis: primes dividing |Sha|
print()
print("=" * _sage_const_80 )
print("SPECIAL: Primes p dividing |Sha|")
print("=" * _sage_const_80 )
print()
print("When p | |Sha|, the p-part of Sha is nontrivial: Sha[p] != 0.")
print("But Sha[p^infty] can still be finite (just = Sha[p] = (Z/pZ)^2).")
print("So we should still have lambda = rank.")
print()

for label, exp_rank, sha_order, sha_struct in sha_curves:
    E = EllipticCurve(label)
    rank = E.rank()

    # Find primes dividing Sha
    sha_primes = [p for p in prime_divisors(sha_order)]

    for p in sha_primes:
        if E.conductor() % p == _sage_const_0 :
            print("{}: p={} divides |Sha|={} but also divides conductor -- skip".format(
                label, p, sha_order))
            continue
        if not E.is_ordinary(p):
            print("{}: p={} divides |Sha|={} but is supersingular -- skip".format(
                label, p, sha_order))
            continue

        try:
            Lp = E.padic_lseries(p)
            series = Lp.series(n=_sage_const_6 )

            lam = None
            for i in range(_sage_const_6 ):
                coeff = series[i]
                if coeff.valuation() < coeff.precision_absolute():
                    lam = i
                    break

            print("{}: p={} divides |Sha|={}, lambda={}, rank={}, match={}".format(
                label, p, sha_order, lam, rank, lam == rank))

            # Also check: does the constant term have valuation > 0?
            # If Sha[p] is nontrivial, then |Sel_p| is larger, which affects
            # the p-adic valuation of g_E(0)
            if rank == _sage_const_0  and lam == _sage_const_0 :
                v0 = series[_sage_const_0 ].valuation()
                print("  v_p(g_E(0)) = {} (nonzero iff p | |Sel_p| = {} * torsion * |Sha[p]|)".format(
                    v0, sha_order))

        except Exception as e:
            print("{}: p={} error: {}".format(label, p, e))

