#!/usr/bin/env sage
"""
Systematic computation of Iwasawa lambda invariants vs algebraic rank.
Tests the key hypothesis: ord_{T=0} L_p(E,T) = rank(E(Q)) for ordinary primes p.
"""


# This file was *autogenerated* from the file compute_lambda.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_60 = Integer(60); _sage_const_6 = Integer(6); _sage_const_100p0 = RealNumber('100.0')
# Test curves spanning ranks 0-3, plus some with nontrivial Sha
test_curves = [
    # (label, expected_rank, expected_sha_order)
    # Rank 0
    ("11a1", _sage_const_0 , _sage_const_1 ),
    ("14a1", _sage_const_0 , _sage_const_1 ),
    ("15a1", _sage_const_0 , _sage_const_1 ),
    ("17a1", _sage_const_0 , _sage_const_1 ),
    ("19a1", _sage_const_0 , _sage_const_1 ),
    ("20a1", _sage_const_0 , _sage_const_1 ),
    ("21a1", _sage_const_0 , _sage_const_1 ),
    ("24a1", _sage_const_0 , _sage_const_1 ),
    ("26a1", _sage_const_0 , _sage_const_1 ),
    ("27a1", _sage_const_0 , _sage_const_1 ),
    # Rank 0 with Sha
    ("571a1", _sage_const_0 , _sage_const_4 ),
    ("681b1", _sage_const_0 , _sage_const_9 ),
    # Rank 1
    ("37a1", _sage_const_1 , _sage_const_1 ),
    ("43a1", _sage_const_1 , _sage_const_1 ),
    ("53a1", _sage_const_1 , _sage_const_1 ),
    ("57a1", _sage_const_1 , _sage_const_1 ),
    ("58a1", _sage_const_1 , _sage_const_1 ),
    ("61a1", _sage_const_1 , _sage_const_1 ),
    ("77a1", _sage_const_1 , _sage_const_1 ),
    ("79a1", _sage_const_1 , _sage_const_1 ),
    ("83a1", _sage_const_1 , _sage_const_1 ),
    ("89a1", _sage_const_1 , _sage_const_1 ),
    # Rank 2
    ("389a1", _sage_const_2 , _sage_const_1 ),
    ("433a1", _sage_const_2 , _sage_const_1 ),
    # Rank 3
    ("5077a1", _sage_const_3 , _sage_const_1 ),
]

primes_test = [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 ]

results = []
header = "{:<10} {:<5} {:<6} {:<4} {:<10} {:<12}".format(
    "Curve", "Rank", "|Sha|", "p", "ord_T Lp", "lambda=rank?"
)
print("=" * _sage_const_60 )
print("ord_{{T=0}} L_p(E,T) vs rank(E(Q))")
print("=" * _sage_const_60 )
print(header)
print("-" * _sage_const_60 )

for label, exp_rank, exp_sha in test_curves:
    try:
        E = EllipticCurve(label)
        rank = E.rank()
    except Exception:
        continue

    for p in primes_test:
        if E.conductor() % p == _sage_const_0 :
            continue
        if not E.is_ordinary(p):
            continue

        try:
            Lp = E.padic_lseries(p)
            n_terms = max(rank + _sage_const_3 , _sage_const_6 )
            series = Lp.series(n=n_terms)

            # Extract order of vanishing
            ord_van = None
            for i in range(n_terms):
                try:
                    coeff = series[i]
                    if coeff.valuation() < coeff.precision_absolute():
                        ord_van = i
                        break
                except Exception:
                    pass

            if ord_van is None:
                ord_str = ">=" + str(n_terms)
                match = "MAYBE"
            else:
                ord_str = str(ord_van)
                match = "YES" if ord_van == rank else "NO"

            results.append((label, rank, exp_sha, p, ord_van, match))
            line = "{:<10} {:<5} {:<6} {:<4} {:<10} {:<12}".format(
                label, rank, exp_sha, p, ord_str, match
            )
            print(line)

        except Exception as e:
            pass

# Summary
print()
print("=" * _sage_const_60 )
print("SUMMARY")
print("=" * _sage_const_60 )
yes_count = sum(_sage_const_1  for r in results if r[_sage_const_5 ] == "YES")
no_count = sum(_sage_const_1  for r in results if r[_sage_const_5 ] == "NO")
maybe_count = sum(_sage_const_1  for r in results if r[_sage_const_5 ] == "MAYBE")
total = len(results)
print("Total tests: {}".format(total))
if total > _sage_const_0 :
    print("lambda = rank: {} ({:.1f}%)".format(yes_count, _sage_const_100p0  * yes_count / total))
    print("lambda != rank: {} ({:.1f}%)".format(no_count, _sage_const_100p0  * no_count / total))
    print("inconclusive: {} ({:.1f}%)".format(maybe_count, _sage_const_100p0  * maybe_count / total))

# Check the no cases
if no_count > _sage_const_0 :
    print()
    print("Cases where lambda != rank:")
    for r in results:
        if r[_sage_const_5 ] == "NO":
            print("  {}: rank={}, |Sha|={}, p={}, ord={}".format(r[_sage_const_0 ], r[_sage_const_1 ], r[_sage_const_2 ], r[_sage_const_3 ], r[_sage_const_4 ]))

# Analyze by rank
print()
print("=" * _sage_const_60 )
print("ANALYSIS BY RANK")
print("=" * _sage_const_60 )
for rk in range(_sage_const_4 ):
    rk_results = [r for r in results if r[_sage_const_1 ] == rk]
    if not rk_results:
        continue
    rk_yes = sum(_sage_const_1  for r in rk_results if r[_sage_const_5 ] == "YES")
    rk_total = len(rk_results)
    print("Rank {}: {}/{} match ({:.1f}%)".format(rk, rk_yes, rk_total, _sage_const_100p0  * rk_yes / rk_total))

# Analyze Sha cases specifically
print()
print("=" * _sage_const_60 )
print("SHA ANALYSIS")
print("=" * _sage_const_60 )
sha_results = [r for r in results if r[_sage_const_2 ] > _sage_const_1 ]
if sha_results:
    for r in sha_results:
        print("  {}: rank={}, |Sha|={}, p={}, ord={}, match={}".format(
            r[_sage_const_0 ], r[_sage_const_1 ], r[_sage_const_2 ], r[_sage_const_3 ], r[_sage_const_4 ], r[_sage_const_5 ]))
    sha_yes = sum(_sage_const_1  for r in sha_results if r[_sage_const_5 ] == "YES")
    print("Curves with nontrivial Sha: {}/{} match".format(sha_yes, len(sha_results)))
else:
    print("No curves with nontrivial Sha had ordinary primes in test set")

